# Generated by Django 4.0.3 on 2022-05-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to='question',
        ),
    ]
